[package]
name = "SkyCast"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"]}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
ureq = { version ="3.1.2", features = ["json"] }
